version: "3.1"

services:
  wordpress:
    image: wordpress:5.7.2
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: heritela
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: heritela
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: heritela
      MYSQL_USER: heritela
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: "1" 
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
